[build]
publish = "public"
command = "make build"
functions = "./functions"


[build.environment]
GO_VERSION = "1.17.2"
GIMME_GO_VERSION = "1.17.2"
GO_IMPORT_PATH = "github.com/leizhenpeng/link-shorter-api"

[[redirects]]
from = "/api/*"
to = '/.netlify/functions/link-shorter-api/:splat'
status = 200
